/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DocumentSnapshotSchema extends BaseModel {
  static $columns = [
    'content',
    'contentFormat',
    'createdAt',
    'documentId',
    'id',
    'sourceDocumentUpdatedAt',
    'version',
  ] as const
  $columns = DocumentSnapshotSchema.$columns
  @column()
  declare content: string
  @column()
  declare contentFormat: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare sourceDocumentUpdatedAt: DateTime | null
  @column()
  declare version: number
}

export class DocumentSchema extends BaseModel {
  static $columns = [
    'content',
    'createdAt',
    'id',
    'latestIndexedVersion',
    'latestSnapshotVersion',
    'spaceId',
    'status',
    'summary',
    'title',
    'updatedAt',
  ] as const
  $columns = DocumentSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latestIndexedVersion: number | null
  @column()
  declare latestSnapshotVersion: number | null
  @column()
  declare spaceId: string
  @column()
  declare status: string
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LegacySpaceOwnerMappingSchema extends BaseModel {
  static $columns = ['mappedAt', 'spaceId', 'userId'] as const
  $columns = LegacySpaceOwnerMappingSchema.$columns
  @column.dateTime()
  declare mappedAt: DateTime
  @column({ isPrimary: true })
  declare spaceId: string
  @column()
  declare userId: number
}

export class RagIndexJobSchema extends BaseModel {
  static $columns = [
    'attemptCount',
    'createdAt',
    'documentId',
    'errorCode',
    'errorMessage',
    'finishedAt',
    'id',
    'lockedAt',
    'requestedByUserId',
    'stage',
    'startedAt',
    'status',
    'targetSnapshotVersion',
    'updatedAt',
  ] as const
  $columns = RagIndexJobSchema.$columns
  @column()
  declare attemptCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentId: string
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare requestedByUserId: number | null
  @column()
  declare stage: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare targetSnapshotVersion: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SpaceMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'spaceId', 'updatedAt', 'userId'] as const
  $columns = SpaceMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare spaceId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SpaceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'summary', 'updatedAt'] as const
  $columns = SpaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare summary: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
